##################################################
# HATCHet3 Snakemake configuration
##################################################

##################################################
# Inputs / outputs
patient_id: sample
bb_dir: "/path/to/bb"
# Output paths (relative to snakemake --directory)
bbc_dir: "bbc"
result_dir: "results"
plot_dir: "summary"
log_dir: "logs"

# Reference
genome_size: ""
# BED file of whitelist regions
region_bed: ""

##################################################
cluster-bins:
  minK: 3
  maxK: 30

##################################################
compute-cn:
  k: null
  diploid: true
  tetraploid: true
  minClone: 2
  maxClone: 4

##################################################
# Resources
threads: 4
